services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ipe_db
      POSTGRES_PASSWORD: postgres
    ports:
      - '54320:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: 'postgres:5432'
      ALLOW_ADDR_REGEX: '.*'
      LOG_TRAFFIC: 'true'
    ports:
      - '54330:80'
    depends_on:
      - postgres

volumes:
  db:
    driver: local
