name: Remove Preview Deployments

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Delete Deployment Environment
      uses: strumwolf/delete-deployment-environment@v3.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: Preview
        onlyRemoveDeployments: true